### ISSUE TITLE
Impossible to save consent

### ISSUE THREAD

**Issue by GildasBillardSenseYou** [ekyna/CookieConsentBundle#1]
Hi, 

There is no $ip value passed on saveCookieConsent function, so ip is always null by default and no consent is saved on BDD.  

File : CookieController (34)

Can you correct it on different tags, especially 8 (I don't have php 8)

Thanks a lot,
Gildas

**Comment by ekyna** [comment]
Hi @GildasBillardSenseYou 
You should [use this bundle](https://github.com/Harborn-digital/cookie-consent-bundle). Mine isn't (and won't be) production ready.

**Comment by GildasBillardSenseYou** [comment]
Hi, thanks for your answer, i switched the plugin.
